# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  unit_tests:
    resource_class: small
    environment:
      GO111MODULE: "off"
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/thetreep/covidtracker
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  build_docker_image:
    resource_class: small
    environment:
      GO111MODULE: "off"
    working_directory: /go/src/github.com/thetreep/covidtracker
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Does docker exist
          command: docker -v
      - run:
          name: Build service for runtime docker image (create volume, copy the sources, build executable, copy the executable locally)
          command: |
            docker create -v /go/src/github.com/thetreep/covidtracker --name sources golang:1.14 /bin/true
            docker cp /go/src/github.com/thetreep/covidtracker sources:/go/src/github.com/thetreep
            docker run --rm -e GO111MODULE="off" --volumes-from sources -w /go/src/github.com/thetreep/covidtracker/cmd/covidtracker golang:1.14 go build -o covidtracker
            docker cp sources:/go/src/github.com/thetreep/covidtracker/cmd/covidtracker/covidtracker /go/src/github.com/thetreep/covidtracker/covidtracker
      - run:
          name: building docker image
          command: docker build --rm=false -t eu.gcr.io/the-treep-api-1525507752734/covidtracker:$CIRCLE_SHA1 .
      - run:
          name: Mkdir docker-cache
          command: mkdir -p docker-cache
      - run:
          name: Save docker image to cache directory
          command: docker save -o docker-cache/built-image.tar eu.gcr.io/the-treep-api-1525507752734/covidtracker:$CIRCLE_SHA1
      - persist_to_workspace:
          root: .
          paths:
            - docker-cache
  deploy_prod:
    resource_class: small
    working_directory: /go/src/github.com/thetreep/covidtracker
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Load docker image from cache
          command: docker load --input docker-cache/built-image.tar
      - run:
          name: Auth gCloud SDK
          command: bash .circleci/gcloud-auth.sh
      - run:
          name: tag docker image with prod
          command: docker tag eu.gcr.io/the-treep-api-1525507752734/covidtracker:$CIRCLE_SHA1 eu.gcr.io/the-treep-api-1525507752734/covidtracker:prod
      - run:
          name: Running prod.sh
          command: bash .circleci/prod.sh
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - unit_tests
      - build_docker_image:
          requires:
            - unit_tests
          filters:
            branches:
              only:
                - master
                - prod
      - deploy_prod:
          context: TheTreep
          requires:
            - build_docker_image
          filters:
            branches:
              only:
                - master
                - prod
